### ISSUE TITLE
File size too large  -- but it isn't

### ISSUE THREAD

**Issue by dbinetti** [klis87/django-cloudinary-storage#14]
I'm trying to upload using the admin, and am getting 
```
cloudinary.api.Error: File size too large. Got 28078738. Maximum is 10485760.
```

However, the file itself is only about 2MB.  It has worked for the longest time and only recently have I seen this error.    Thoughts?

**Comment by dbinetti** [comment]
Here is the full trace:

```
Traceback (most recent call last):
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 574, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1556, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1450, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1490, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/fsm_admin/mixins.py", line 189, in save_model
    super(FSMTransitionMixin, self).save_model(request, obj, form, change)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1026, in save_model
    obj.save()
  File "/Users/dbinetti/repos/barberscore-api/project/api/models/group.py", line 427, in save
    super().save(*args, **kwargs)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 820, in _save_table
    for f in non_pks]
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 820, in <listcomp>
    for f in non_pks]
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 287, in pre_save
    file.save(file.name, file.file, save=False)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/django/core/files/storage.py", line 49, in save
    return self._save(name, content)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/cloudinary_storage/storage.py", line 70, in _save
    response = self._upload(name, content)
  File "/Users/dbinetti/repos/barberscore-api/project/api/storages.py", line 16, in _upload
    return cloudinary.uploader.upload(content, **options)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/cloudinary/uploader.py", line 40, in upload
    return call_api("upload", params, file=file, **options)
  File "/Users/dbinetti/repos/barberscore-api/.venv/lib/python3.6/site-packages/cloudinary/uploader.py", line 279, in call_api
    raise Error(result["error"]["message"])
cloudinary.api.Error: File size too large. Got 28078738. Maximum is 10485760.

```

**Comment by klis87** [comment]
Where did you set limit 2MB, in Django? Maybe you exceeded Cloudinary limits?

**Comment by dbinetti** [comment]
Both the Django limit and the Cloudinary limit are 10MB.  Is it possible
the file is being "expanded" into a larger size as part of the storage
upload?

It takes a long time to upload, much more than should be for a small file.
So it acts like a 20MB file in all respects -- long upload, fails
validation on file size --- but it isn't!

Grasping at straws here...

**Comment by klis87** [comment]
@dbinetti I guess you upload the file first to django server, then to cloudinary?

**Comment by dbinetti** [comment]
I'm asking you -- that's handled by the storage engine, right?  :-P

Cheekiness aside, I'm not wholly certain of the internals.  This is the
Django admin, so that's probably the approach.  Before I used your library
I went with everything done in memory.  but now I just this backend.

**Comment by klis87** [comment]
Ok, so this means yes :) I think the best would be to debug what file you get on your django server in `upload` method in storage you use. Check what file size is there. But I guess it is less that 10 mb as it would trigger Django error, not Cloudinary. Thats really weird I must admit.

**Comment by dbinetti** [comment]
yeah, normal size.  very strange.  

I've had some other problems related to recent Heroku build pack changes -- everything kind of broke at once.  so it might be related to that.  closing for now since I can't find anything wrong with this lib.
